name: Build APK

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install buildozer
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-wheel
        pip install buildozer cython virtualenv
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: mp4_spy-apk
        path: bin/*.apk
